# Copyright 2017 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: "3.8"

services:
  gateway:
    container_name: kong-gateway
    image: kong/kong-gateway:3.6.0.0
    environment:
      - "KONG_DATABASE=off"
      - "KONG_PROXY_ACCESS_LOG=/dev/stdout"
      - "KONG_DECLARATIVE_CONFIG=/kong/declarative/kong.yml"
      - "KONG_ADMIN_ACCESS_LOG=/dev/stdout"
      - "KONG_PROXY_ERROR_LOG=/dev/stderr"
      - "KONG_ADMIN_ERROR_LOG=/dev/stderr"
      - "KONG_PROXY_LISTEN=0.0.0.0:7000 reuseport backlog=16384, 0.0.0.0:7443 http2 ssl reuseport backlog=16384"
      - "KONG_DNS_ORDER=LAST,A,CNAME"
    volumes:
      - ${PWD}/hack/gateway/kong.yml:/kong/declarative/kong.yml

  api:
    container_name: dashboard-api
    build:
      context: ../../modules
      dockerfile: api/dev.Dockerfile
    command:
      --kubeconfig=${KUBECONFIG:?}
      --sidecar-host=${SIDECAR_HOST:?}
      --token-ttl=${TOKEN_TTL:?}
    volumes:
      - ${KUBECONFIG:?}:${KUBECONFIG:?}
      - ${PWD}/modules:/workspace
    tmpfs:
      - /tmp

  web-go:
    container_name: dashboard-web-go
    build:
      context: ../../modules
      dockerfile: web/dev.go.Dockerfile
    command:
      - "--locale-config=/public/locale_conf.json"
      - "--system-banner=${SYSTEM_BANNER:?}"
      - "--system-banner-severity=${SYSTEM_BANNER_SEVERITY:?}"
    volumes:
      - ${PWD}/modules:/workspace
    tmpfs:
      - /tmp

  web-angular:
    container_name: dashboard-web-angular
    build:
      context: ../../modules/web
      dockerfile: dev.web.Dockerfile
    volumes:
      - ${PWD}/modules/web:/workspace
    ports:
      - "8080:8080"

  scraper:
    container_name: metrics-scraper
    build:
      context: ../../modules/metrics-scraper
      dockerfile: dev.Dockerfile
    command:
      --kubeconfig=${KUBECONFIG:?}
      --metric-resolution=5s
      --metric-duration=10m
    volumes:
      - ${KUBECONFIG:?}:${KUBECONFIG:?}
    tmpfs:
      - /tmp

networks:
  default:
    name: kind
    external: true
